[package]
name = "tusks"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
tusks-macro.workspace = true
tusks-lib.workspace = true
tusks-tasks.workspace = true

[features]
debug = ["tusks-macro/debug"]
