[package]
name = "tusks"
version = "1.2.2"
edition = "2024"

[dependencies]
tusks-macro = { path = "../tusks-macro" }
tusks-lib = { path = "../tusks-lib" }
indexmap = "2.12.1"

[features]
debug = ["tusks-macro/debug"]
